### PR TITLE
actually load migrations when initializing the engine

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
cc @ares something you forgot the last time ;)

**Comment by evgeni** [comment]
The tests pass after https://github.com/theforeman/foreman/pull/9499 has been applied :woman_facepalming:

**Comment by ekohl** [comment]
[test foreman_host_extra_validator]

**Review by ekohl — APPROVED** [review]

**Comment by ekohl** [comment]
The tests should be fixed, but for now I think this doesn't introduce further regressions.

**Pull request merged**
