### PR TITLE
fix Style/ExpandPathArguments cop

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by timogoebel** [comment]
[test foreman_host_extra_validator]

**Comment by timogoebel** [comment]
[test foreman_host_extra_validator]

**Comment by timogoebel** [comment]
[test foreman_host_extra_validator]

**Comment by mmoll** [comment]
:green_heart:

**Comment by timogoebel** [comment]
Danke, @mmoll.

**Pull request merged**
